version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo:27017
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata
    ports:
      - "27017:27017"